name: Lint Pull Requests

on:
  pull_request:
    types: [opened, synchronize, edited, ready_for_review]


jobs:
  lint-pr-title:
    runs-on: ubuntu-latest
    steps:
      # Check the PR title meets some criteria
      - uses: deepakputhraya/action-pr-title@master
        with:
          regex: 'BFS-[0-9]{1,5}(,[\s]*DHP-[0-9]{1,5})*:.*'
          min_length: 9
          github_token: ${{ github.token }}